### ISSUE TITLE
nomnom@1.8.1: Package no longer supported

### ISSUE THREAD

**Issue by Deep-NC** [tidev/alloy#1343]
![image](https://user-images.githubusercontent.com/107190363/172844304-a5caeaa7-be10-4f5d-9792-f997404cd9d0.png)

**Comment by Deep-NC** [comment]
@[cb1kenobi](https://github.com/tidev/alloy/commits?author=cb1kenobi)
cb1kenobi

**Comment by cb1kenobi** [comment]
Yeah, nomnom has been dead for a long time. The plan is to carefully merge the Alloy CLI into the Titanium CLI and thus this will no longer be an issue. However, it's going to be a while before we accomplish this.

**Comment by m1ga** [comment]
I looks like one of the packages that is including nomnom is jsonlint: https://github.com/zaach/jsonlint
it hasn't been updated and there is a fork https://github.com/prantlf/jsonlint that replaces nomnom with commander. I didn't test that yet but it looks like something we should test for a quicker change.
