### ISSUE TITLE
PickerColumn data binding makes reference to undefined function ".getRows()"

### ISSUE THREAD

**Issue by caufang** [tidev/alloy#1348]
Here is a reference to the line in question:
https://github.com/tidev/alloy/blob/5e9e25e58ce0fac3e8c12e7583297a5f64d27101/Alloy/commands/compile/parsers/Ti.UI.PickerColumn.js#L75

I'm pretty sure this should just be referencing the `.rows` property.

I believe that until this is fixed, out-of-the-box data binding on PickerColumn is broken.

---

For others that might find this through searching and still waiting for a fix:

I've been patching this using the module attribute in the XML to intercept PickerColumn creation and add a proxy `.getRows()` function.

https://titaniumsdk.com/guide/Alloy_Framework/Alloy_Guide/Alloy_Views/Alloy_XML_Markup.html#module-attribute

XML using module attribute:
`<Column module="picker_fixer" ...`

picker_fixer.js:
```
export const createPickerColumn = function picker_fixer(args) {

  const picker_column = Ti.UI.createPickerColumn(args);

  picker_column.getRows = function () {

    return this.rows;
  };

  return picker_column;
};
```

**Comment by m1ga** [comment]
good catch @caufang 
I'll added a PR https://github.com/tidev/alloy/pull/1350 but I still need to check it with a test app.

Thanks for reporting
